name: Check Contributor Links

on:
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install lychee
        run: |
          curl -Ls https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz \
          | tar xz
          sudo mv lychee /usr/local/bin/

      - name: Run link checker
        run: lychee --verbose --no-progress .